-- begin SATTR7_BUSINESS_USER
alter table SATTR7_BUSINESS_USER add constraint FK_SATTR7_BUSINESS_USER_ON_SYS_USER foreign key (SYS_USER_ID) references SEC_USER(ID)^
alter table SATTR7_BUSINESS_USER add constraint FK_SATTR7_BUSINESS_USER_ON_COMPANY foreign key (COMPANY_ID) references SATTR7_COMPANY(ID)^
create index IDX_SATTR7_BUSINESS_USER_ON_SYS_USER on SATTR7_BUSINESS_USER (SYS_USER_ID)^
create index IDX_SATTR7_BUSINESS_USER_ON_COMPANY on SATTR7_BUSINESS_USER (COMPANY_ID)^
-- end SATTR7_BUSINESS_USER
